import {categories,groups,validateBatch,mergeHistory,historySummary} from './history.mjs';
const key='entrenos-personal-history-v1';let rows=[];try{rows=JSON.parse(localStorage.getItem(key)||'[]')}catch{}let draft=null,month='',filter='',query='';
const modal=document.createElement('dialog');modal.id='history-modal';modal.setAttribute('aria-labelledby','history-title');document.body.append(modal);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>x===null?'Valor não informado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(x/100);
function save(){localStorage.setItem(key,JSON.stringify(rows))}function show(title,body){modal.innerHTML=`<div class="modalhead"><h2 id="history-title">${title}</h2><button data-h="close" aria-label="Fechar">✕</button></div>${body}`;if(!modal.open)modal.showModal()}
function entry(x){return `<button class="row" data-h="detail" data-id="${esc(x.id)}"><span class="description"><strong>${esc(x.name)}</strong><small>${esc(x.month)} · ${esc(x.category)}<br>${x.source==='Compra informada'?'Compra registrada · conferir fatura':x.paid?'OK · pago, data desconhecida':'Status não informado'}${x.review?.length?' · Revisar':''}</small></span><span class="amount">${money(x.amount)}</span></button>`}
function open(){const list=rows.filter(x=>(!month||x.month===month)&&(!filter||x.category===filter)&&x.name.toLowerCase().includes(query.toLowerCase()));const t=historySummary(list);show('Minha planilha',`<p class="note">Histórico pessoal salvo apenas neste navegador. Não é enviado ao GitHub ou a um servidor. Saldo bancário e datas de pagamento não foram inferidos.</p><div class="actions"><button class="primary" data-h="load">Importar arquivo privado</button><button class="outline" data-h="export">Exportar cópia pessoal</button></div><div class="filters"><select id="h-month" aria-label="Mês"><option value="">Todos os meses</option>${[...new Set(rows.map(x=>x.month))].sort().map(v=>`<option ${v===month?'selected':''}>${v}</option>`).join('')}</select><select id="h-category" aria-label="Categoria"><option value="">Todas as categorias</option>${[...new Set([...categories,...rows.map(x=>x.category)])].map(v=>`<option ${v===filter?'selected':''}>${esc(v)}</option>`).join('')}</select></div><p class="note">${t.count} registros · Soma dos valores informados: ${money(t.known)}<br>${t.missing} sem valor · ${t.review} com pendências. Soma documental; não representa saldo ou total validado de despesas.</p><div>${list.map(entry).join('')||'<p class="empty">Importe o arquivo privado preparado a partir da sua planilha.</p>'}</div><button class="outline section" data-h="install">Instalar no iPhone</button>`)}
function preview(){const t=historySummary(draft.items);show('Conferir importação',`<p class="note">${t.count} registros de janeiro a agosto de 2026. ${t.missing} sem valor. Categorias são sugestões editáveis; a planilha não vinculava gastos aos grupos do orçamento. OK preservado como pago, sem inventar data, conta ou forma.</p><p class="note">Registros do bloco Sarah de janeiro/fevereiro ficam sinalizados para esclarecer sua relação com o quadro temporário. Valores FATURA e campos vazios permanecem em revisão. Nenhuma parcela futura será gerada.</p>${draft.items.map(entry).join('')}<div class="actions"><button class="primary" data-h="commit">Confirmar histórico neste aparelho</button></div>`)}
const picker=document.createElement('input');picker.type='file';picker.accept='.json,application/json';picker.hidden=true;document.body.append(picker);
function purchase(params=new URLSearchParams()){show('Categorizar compra',`<p class="note">Confira os dados antes de registrar. Esta entrada não consulta bancos, não envia dinheiro e não liquida uma fatura.</p><form id="history-purchase"><input type="hidden" name="ref" value="${esc(params.get('ref')||'')}"><label for="purchase-name">Descrição / estabelecimento</label><input id="purchase-name" name="name" maxlength="100" required value="${esc(params.get('descricao')||'')}"><label for="purchase-amount">Valor (R$)</label><input id="purchase-amount" name="amount" type="number" min="0.01" step="0.01" required value="${esc(params.get('valor')||'')}"><label for="purchase-date">Data da compra</label><input id="purchase-date" name="date" type="date" required value="${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}-${String(new Date().getDate()).padStart(2,'0')}"><label for="purchase-category">Categoria</label><select name="category" id="purchase-category">${categories.map(c=>`<option>${c}</option>`).join('')}</select><label for="purchase-group">Grupo do orçamento</label><select name="budgetGroup" id="purchase-group">${groups.map(c=>`<option>${c}</option>`).join('')}</select><div class="actions"><button class="primary">Salvar no histórico pessoal</button></div></form>`)}
document.addEventListener('submit',e=>{if(e.target.id!=='history-purchase')return;e.preventDefault();e.stopImmediatePropagation();try{const d=Object.fromEntries(new FormData(e.target));const amount=Math.round(Number(d.amount)*100);if(!Number.isSafeInteger(amount)||amount<=0)throw Error('Informe um valor válido.');const id=d.ref?'shortcut:'+d.ref:crypto.randomUUID();if(rows.some(x=>x.id===id))throw Error('Esta referência já foi registrada.');rows.push({id,name:d.name.trim(),amount,month:d.date.slice(0,7),purchaseDate:d.date,rawAmount:d.amount,paid:false,date:null,category:d.category,budgetGroup:d.budgetGroup,suggestedCategory:d.category,source:'Compra informada',block:'Pessoal',review:['Conferir pagamento / fatura']});save();month=d.date.slice(0,7);filter='';open()}catch(error){show('Confira a compra',`<p>${esc(error.message)}</p>`)}},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-h="purchase"]'))purchase()});
new MutationObserver(()=>{if(modal.querySelector('[data-h="load"]')&&!modal.querySelector('[data-h="purchase"]')){const b=document.createElement('button');b.className='primary';b.dataset.h='purchase';b.textContent='＋ Registrar compra';modal.querySelector('.actions').prepend(b)}}).observe(modal,{childList:true});
function receivePurchase(){if(!location.hash.startsWith('#compra?'))return;const params=new URLSearchParams(location.hash.slice(8));history.replaceState(null,'',location.pathname+location.search);purchase(params)}
window.addEventListener('hashchange',receivePurchase);receivePurchase();
picker.addEventListener('change',async()=>{try{if(!picker.files[0])return;if(picker.files[0].size>3000000)throw Error('Arquivo muito grande.');draft=validateBatch(JSON.parse(await picker.files[0].text()));preview()}catch(e){show('Não foi possível importar',`<p>${esc(e.message)}</p>`)}finally{picker.value=''}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-h]');if(!b)return;const a=b.dataset.h,id=b.dataset.id;try{
if(a==='open')open();if(a==='close')modal.close();if(a==='load')picker.click();
if(a==='commit'){rows=mergeHistory(rows,draft);save();draft=null;open()}
if(a==='detail'){const x=(draft?.items||rows).find(x=>x.id===id);show(esc(x.name),`<p class="note">Origem: ${esc(x.source)} · ${esc(x.block)}<br>Valor original: ${esc(x.rawAmount)}<br>${x.paid?'Pago conforme OK; liquidação não informada.':'Status original vazio; não classificamos como vencido.'}<br>${esc((x.review||[]).join(' · '))}</p><form id="history-edit" data-id="${esc(id)}"><label for="h-edit-category">Categoria</label><input id="h-edit-category" name="category" list="h-categories" value="${esc(x.category)}" required maxlength="60"><datalist id="h-categories">${categories.map(c=>`<option value="${esc(c)}">`).join('')}</datalist><p class="note">Sugestão: ${esc(x.suggestedCategory)}. Você pode escrever uma categoria própria.</p><label for="h-group">Grupo da planilha</label><select name="budgetGroup" id="h-group">${groups.map(g=>`<option ${g===x.budgetGroup?'selected':''}>${g}</option>`).join('')}</select><div class="actions"><button class="primary">Salvar classificação</button></div></form>`)}
if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify({format:'entrenos-history-v1',items:rows},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='entre-nos-historico-privado.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
if(a==='install')show('No seu iPhone',`<p class="note">Abra o endereço publicado no Safari → Compartilhar → Adicionar à Tela de Início → mantenha Abrir como App ativado, quando disponível → Adicionar.</p><p class="note">Abra pelo novo ícone e importe o arquivo privado em Minha planilha. Cada aparelho mantém sua própria cópia. Exporte uma cópia de segurança antes de limpar os dados do navegador.</p>`);
}catch(error){show('Confira os dados',`<p>${esc(error.message)}</p>`)}});
document.addEventListener('submit',e=>{if(e.target.id!=='history-edit')return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(e.target));const x=(draft?.items||rows).find(x=>x.id===e.target.dataset.id);x.category=d.category.trim()||'A categorizar';x.budgetGroup=d.budgetGroup;if(draft)preview();else{save();open()}},true);
modal.addEventListener('change',e=>{if(e.target.id==='h-month'){month=e.target.value;open()}if(e.target.id==='h-category'){filter=e.target.value;open()}});
function attach(){const top=document.querySelector('.heading');if(top&&!top.querySelector('[data-h]')){const b=document.createElement('button');b.className='outline personal-shortcut';b.dataset.h='open';b.textContent='Minha planilha';top.append(b)}}
new MutationObserver(attach).observe(document.querySelector('#app'),{childList:true});attach();

